ALTER TABLE "content" ADD COLUMN "created_at" TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE "content" ADD COLUMN "updated_at" TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE "content" ADD COLUMN "published_at" TIMESTAMP;
